language: python
python:
  - "3.6"
env:
  - DJANGO_VERSION=2.1
# command to install dependencies
install:
  - pip install -r requirements/test.txt
  - pip install -I Django==$DJANGO_VERSION
# command to run tests
script:
  - cd $TRAVIS_BUILD_DIR && ./manage.py test
